In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("/content/covid_toy.csv")

In [4]:
data.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [9]:
value_counts = data['city'].value_counts()

In [10]:
value_counts

Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: city, dtype: int64

In [11]:
data['gender'].value_counts()

Female    59
Male      41
Name: gender, dtype: int64

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        100 non-null    int64  
 1   gender     100 non-null    object 
 2   fever      90 non-null     float64
 3   cough      100 non-null    object 
 4   city       100 non-null    object 
 5   has_covid  100 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB


In [15]:
x=data.iloc[:,0:5]

In [16]:
x

age  gender  fever   cough       city
0    60    Male  103.0    Mild    Kolkata
1    27    Male  100.0    Mild      Delhi
2    42    Male  101.0    Mild      Delhi
3    31  Female   98.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
95   12  Female  104.0    Mild  Bangalore
96   51  Female  101.0  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore
98    5  Female   98.0  Strong     Mumbai
99   10  Female   98.0  Strong    Kolkata

[100 rows x 5 columns]

In [17]:
y=data.iloc[:,-1]

In [18]:
y

0      No
1     Yes
2      No
3      No
4      No
     ... 
95     No
96    Yes
97     No
98     No
99    Yes
Name: has_covid, Length: 100, dtype: object

In [14]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1)

In [23]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 90 entries, 90 to 42
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     90 non-null     int64  
 1   gender  90 non-null     object 
 2   fever   80 non-null     float64
 3   cough   90 non-null     object 
 4   city    90 non-null     object 
dtypes: float64(1), int64(1), object(3)
memory usage: 4.2+ KB


In [24]:
fever=x_train.iloc[:,2:3]

In [25]:
fever

fever
90   99.0
35  102.0
98   98.0
13  102.0
94    NaN
..    ...
74  104.0
66  104.0
26  100.0
68  104.0
42  100.0

[90 rows x 1 columns]

In [27]:
from sklearn.impute import SimpleImputer

In [28]:
imputer=SimpleImputer()

In [29]:
fever1=imputer.fit_transform(fever)

In [33]:
from sklearn.preprocessing import OrdinalEncoder

In [35]:
ordinal=OrdinalEncoder(categories=[['Mild','Strong']])

In [36]:
ordinal1=x_train.iloc[:,3:4]

In [37]:
ordinal1

cough
90  Strong
35  Strong
98  Strong
13    Mild
94  Strong
..     ...
74  Strong
66    Mild
26    Mild
68  Strong
42    Mild

[90 rows x 1 columns]

In [38]:
ordinal_new=ordinal.fit_transform(ordinal1)

In [39]:
ordinal_new

array([[1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],

In [41]:
from sklearn.preprocessing import OneHotEncoder

In [43]:
onehotencoder=OneHotEncoder(drop='first',sparse=False)

In [46]:
onehotencoder.fit_transform(x_train[['gender','city']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],


In [45]:
x_train

age  gender  fever   cough       city
90   59  Female   99.0  Strong      Delhi
35   82  Female  102.0  Strong  Bangalore
98    5  Female   98.0  Strong     Mumbai
13   64    Male  102.0    Mild  Bangalore
94   79    Male    NaN  Strong    Kolkata
..  ...     ...    ...     ...        ...
74   34  Female  104.0  Strong      Delhi
66   51    Male  104.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
68   54  Female  104.0  Strong    Kolkata
42   27    Male  100.0    Mild      Delhi

[90 rows x 5 columns]

Simple Imputer on dataset-x_train,x_test

In [52]:
fever3=x_train.iloc[:, 2:3]

In [53]:
fever3

fever
90   99.0
35  102.0
98   98.0
13  102.0
94    NaN
..    ...
74  104.0
66  104.0
26  100.0
68  104.0
42  100.0

[90 rows x 1 columns]

In [54]:
fever4=x_test.iloc[:,2:3]

In [55]:
fever4

fever
52  100.0
3    98.0
18   98.0
70  101.0
69  103.0
6   101.0
34  102.0
12   99.0
24  100.0
1   100.0

In [59]:
from sklearn.impute import SimpleImputer

In [60]:
impute=SimpleImputer()

In [61]:
fever_x_train=impute.fit_transform(fever3)

In [62]:
fever_x_train

array([[ 99.   ],
       [102.   ],
       [ 98.   ],
       [102.   ],
       [100.925],
       [ 98.   ],
       [100.925],
       [ 99.   ],
       [ 98.   ],
       [101.   ],
       [100.925],
       [100.925],
       [100.925],
       [103.   ],
       [ 98.   ],
       [100.   ],
       [103.   ],
       [104.   ],
       [103.   ],
       [102.   ],
       [104.   ],
       [ 98.   ],
       [101.   ],
       [104.   ],
       [ 99.   ],
       [101.   ],
       [101.   ],
       [101.   ],
       [101.   ],
       [ 99.   ],
       [ 99.   ],
       [ 98.   ],
       [ 98.   ],
       [104.   ],
       [101.   ],
       [ 98.   ],
       [ 99.   ],
       [103.   ],
       [102.   ],
       [102.   ],
       [102.   ],
       [ 99.   ],
       [100.   ],
       [101.   ],
       [101.   ],
       [101.   ],
       [ 98.   ],
       [102.   ],
       [101.   ],
       [100.   ],
       [ 98.   ],
       [104.   ],
       [104.   ],
       [100.   ],
       [100.925],
       [10

In [63]:
fever_x_test=impute.transform(fever4)

In [64]:
fever_x_test

array([[100.],
       [ 98.],
       [ 98.],
       [101.],
       [103.],
       [101.],
       [102.],
       [ 99.],
       [100.],
       [100.]])

In [ ]:
fever_x_train
fever_x_test

In [68]:
from sklearn.preprocessing import OrdinalEncoder

In [70]:
ordinal_data=x_train.iloc[:,3:4]

In [71]:
ordinal_data

cough
90  Strong
35  Strong
98  Strong
13    Mild
94  Strong
..     ...
74  Strong
66    Mild
26    Mild
68  Strong
42    Mild

[90 rows x 1 columns]

In [72]:
ordinal=OrdinalEncoder(categories=[['Mild','Strong']])

In [73]:
ordinal_x_train=ordinal.fit(ordinal_data)

In [74]:
ordinal_data1=x_test.iloc[:,3:4]

In [75]:
ordinal_x_test=ordinal.fit_transform(ordinal_data1)

In [79]:

ordinal_x_test

array([[1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.]])

In [78]:
ordinal_x_train

OrdinalEncoder(categories=[['Mild', 'Strong']])

In [82]:
from sklearn.compose import ColumnTransformer

In [84]:
transformer=ColumnTransformer(transformers=[('tnf1',SimpleImputer(),['fever']),
('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [86]:
x_train1=transformer.fit_transform(x_train)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [87]:
x_train1

array([[ 99.   ,   1.   ,   0.   ,   1.   ,   0.   ,   0.   ,  59.   ],
       [102.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ,  82.   ],
       [ 98.   ,   1.   ,   0.   ,   0.   ,   0.   ,   1.   ,   5.   ],
       [102.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ,  64.   ],
       [100.925,   1.   ,   1.   ,   0.   ,   1.   ,   0.   ,  79.   ],
       [ 98.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ,  80.   ],
       [100.925,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,  84.   ],
       [ 99.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ,  49.   ],
       [ 98.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ,  65.   ],
       [101.   ,   0.   ,   1.   ,   1.   ,   0.   ,   0.   ,  19.   ],
       [100.925,   1.   ,   0.   ,   0.   ,   0.   ,   1.   ,  20.   ],
       [100.925,   1.   ,   0.   ,   0.   ,   0.   ,   1.   ,  34.   ],
       [100.925,   0.   ,   1.   ,   0.   ,   0.   ,   1.   ,  23.   ],
       [103.   ,   1.   ,   1.   ,   0.   ,   1.   ,   0.   ,  7

In [88]:
x_train

age  gender  fever   cough       city
90   59  Female   99.0  Strong      Delhi
35   82  Female  102.0  Strong  Bangalore
98    5  Female   98.0  Strong     Mumbai
13   64    Male  102.0    Mild  Bangalore
94   79    Male    NaN  Strong    Kolkata
..  ...     ...    ...     ...        ...
74   34  Female  104.0  Strong      Delhi
66   51    Male  104.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
68   54  Female  104.0  Strong    Kolkata
42   27    Male  100.0    Mild      Delhi

[90 rows x 5 columns]

In [89]:
x_test1=transformer.fit_transform(x_test)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
